FROM localhost/oci-nix-entrypoint:0.0.1 AS test-nix-entrypoint


WORKDIR /home/nixuser

# https://github.com/moby/moby/issues/35783#issuecomment-355981140
RUN echo \
 && chmod 1777 /tmp \
 && test -d /var/empty || mkdir -pv /var/empty \
 && ssh-keygen -A \
 && chmod -R 0700 /nix \
 && chmod -Rv 0700 /home/nixuser \
 && chown -R nixuser:nixgroup /nix \
 && chown -Rv nixuser:nixgroup /home/nixuser \
 && chown -v 0:0 \
          /bin/sudo \
          /nix/store/*-sudo-1.9.10/libexec/sudo/sudoers.so \
 && chmod -v u+s \
          /sbin/sudo \
          /nix/store/*-shadow*su/bin/su \
 && echo 'Yes, the sudo password is hardcoded! It is an sandbox/playground OCI.' \
 && echo 'nixuser ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/nixuser

# && echo 'nixuser:123' | chpasswd \

EXPOSE 22

# CMD ["/bin/sshd", "-D"]
# USER nixuser

# RUN echo \
#  && nix flake --version \
#  && nix flake metadata nixpkgs | tee "${HOME}"/metadata.txt \
#  && cat "${HOME}"/metadata.txt

# COPY ./src/pkgs/oci-nix-bash-coreutils-ca-bundle-etc-passwd-etc-group-tmp-sudo-su/scripts/nix-build-minimal-iso.sh "${HOME}"
#
# WORKDIR "${HOME}"
#
# RUN ./nix-build-minimal-iso.sh \
#      && nix store gc -v



FROM localhost/test-nix-entrypoint AS with-iso

# groupadd --system nixbld \
# RUN groupadd --system nixbld \
#  && for n in $(seq 1 30); do \
#     useradd \
#     --comment "Nix build user $n" \
#     --gid nixbld \
#     --groups nixbld \
#     --home-dir /var/empty \
#     --no-create-home \
#     --no-user-group \
#     --shell "$(which nologin)" \
#     --system \
#     nixbld$n; done

# RUN nix --option sandbox false profile install --refresh nixpkgs#hello \
# && hello

# USER 0
#
# RUN nix --option sandbox false profile install --refresh github:ES-Nix/nix-qemu-kvm/dev \
#  && nix store gc -v
#
# USER nixuser
#
# ENTRYPOINT entrypoint
