FROM docker.io/library/ubuntu:16.04


RUN apt-get update \
 && apt-get install --no-install-recommends --no-install-suggests -y \
    ca-certificates \
    curl \
    sudo \
    tar \
    xz-utils \
    openssh-server \
 && apt-get -y autoremove \
 && apt-get -y clean \
 && rm -rf /var/lib/apt/lists/*


RUN mkdir -pv /var/run/sshd \
 && echo 'root:1' | chpasswd \
 && sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config \
 && sed -i 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' /etc/pam.d/sshd \
 && sed -i 's/PermitEmptyPasswords no/PermitEmptyPasswords yes/' /etc/ssh/sshd_config


RUN addgroup nixgroup \
 && adduser \
    --quiet \
    --disabled-password \
    --shell /bin/bash \
    --home /home/nixuser \
    --gecos "User" nixuser \
    --ingroup nixgroup \
 && usermod -a -G sudo nixuser \
 && echo "nixuser:123" | chpasswd \
 && echo 'nixuser ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers \
 && chmod 0700 /home/nixuser \
 && mkdir -p /home/nixuser/tmp \
 && chown -R nixuser: /home/nixuser/tmp

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
