FROM localhost/nix-busybox-sandbox-shell-ca-bundle-etc-passwd-etc-group-tmp:0.0.1 AS test-nix


WORKDIR /home/nixuser

# https://github.com/moby/moby/issues/35783#issuecomment-355981140
RUN echo \
 && chmod 1777 /tmp \
 && chmod -R 0700 /nix \
 && chmod -Rv 0700 /home/nixuser

# RUN chown -R nixuser:nixgroup /nix \
#  && chown -Rv nixuser:nixgroup /home/nixuser

USER nixuser

# RUN echo \
#  && nix flake --version \
#  && nix flake metadata nixpkgs | tee "${HOME}"/metadata.txt \
#  && cat "${HOME}"/metadata.txt

# COPY ./src/pkgs/oci-nix-bash-coreutils-ca-bundle-etc-passwd-etc-group-tmp-sudo-su/scripts/nix-build-minimal-iso.sh "${HOME}"
#
# WORKDIR "${HOME}"
#
# RUN ./nix-build-minimal-iso.sh \
#      && nix store gc -v

